// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "qos_token/v1/Claims.proto" (package "discord_protos.qos_token.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message discord_protos.qos_token.v1.Claims
 */
export interface Claims {
    /**
     * @generated from protobuf field: fixed64 user_id = 1
     */
    userId: bigint;
    /**
     * @generated from protobuf field: fixed64 issued_at = 2
     */
    issuedAt: bigint;
    /**
     * @generated from protobuf field: bool is_staff = 3
     */
    isStaff: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class Claims$Type extends MessageType<Claims> {
    constructor() {
        super("discord_protos.qos_token.v1.Claims", [
            { no: 1, name: "user_id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "issued_at", kind: "scalar", T: 6 /*ScalarType.FIXED64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "is_staff", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Claims>): Claims {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0n;
        message.issuedAt = 0n;
        message.isStaff = false;
        if (value !== undefined)
            reflectionMergePartial<Claims>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Claims): Claims {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 user_id */ 1:
                    message.userId = reader.fixed64().toBigInt();
                    break;
                case /* fixed64 issued_at */ 2:
                    message.issuedAt = reader.fixed64().toBigInt();
                    break;
                case /* bool is_staff */ 3:
                    message.isStaff = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Claims, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 user_id = 1; */
        if (message.userId !== 0n)
            writer.tag(1, WireType.Bit64).fixed64(message.userId);
        /* fixed64 issued_at = 2; */
        if (message.issuedAt !== 0n)
            writer.tag(2, WireType.Bit64).fixed64(message.issuedAt);
        /* bool is_staff = 3; */
        if (message.isStaff !== false)
            writer.tag(3, WireType.Varint).bool(message.isStaff);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.qos_token.v1.Claims
 */
export const Claims = new Claims$Type();
