// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "qos_token/v1/QosToken.proto" (package "discord_protos.qos_token.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message discord_protos.qos_token.v1.QosToken
 */
export interface QosToken {
    /**
     * @generated from protobuf field: optional discord_protos.qos_token.v1.QosToken.ClientProvidedQosData client_provided = 1
     */
    clientProvided?: QosToken_ClientProvidedQosData;
    /**
     * @generated from protobuf field: optional discord_protos.qos_token.v1.QosToken.DerivedQosData derived = 2
     */
    derived?: QosToken_DerivedQosData;
}
/**
 * @generated from protobuf message discord_protos.qos_token.v1.QosToken.ClientProvidedQosData
 */
export interface QosToken_ClientProvidedQosData {
    /**
     * @generated from protobuf field: bool is_active = 1
     */
    isActive: boolean;
}
/**
 * @generated from protobuf message discord_protos.qos_token.v1.QosToken.DerivedQosData
 */
export interface QosToken_DerivedQosData {
    /**
     * @generated from protobuf field: bytes claims = 1
     */
    claims: Uint8Array;
}
// @generated message type with reflection information, may provide speed optimized methods
class QosToken$Type extends MessageType<QosToken> {
    constructor() {
        super("discord_protos.qos_token.v1.QosToken", [
            { no: 1, name: "client_provided", kind: "message", T: () => QosToken_ClientProvidedQosData },
            { no: 2, name: "derived", kind: "message", T: () => QosToken_DerivedQosData }
        ]);
    }
    create(value?: PartialMessage<QosToken>): QosToken {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<QosToken>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QosToken): QosToken {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional discord_protos.qos_token.v1.QosToken.ClientProvidedQosData client_provided */ 1:
                    message.clientProvided = QosToken_ClientProvidedQosData.internalBinaryRead(reader, reader.uint32(), options, message.clientProvided);
                    break;
                case /* optional discord_protos.qos_token.v1.QosToken.DerivedQosData derived */ 2:
                    message.derived = QosToken_DerivedQosData.internalBinaryRead(reader, reader.uint32(), options, message.derived);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QosToken, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional discord_protos.qos_token.v1.QosToken.ClientProvidedQosData client_provided = 1; */
        if (message.clientProvided)
            QosToken_ClientProvidedQosData.internalBinaryWrite(message.clientProvided, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.qos_token.v1.QosToken.DerivedQosData derived = 2; */
        if (message.derived)
            QosToken_DerivedQosData.internalBinaryWrite(message.derived, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.qos_token.v1.QosToken
 */
export const QosToken = new QosToken$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QosToken_ClientProvidedQosData$Type extends MessageType<QosToken_ClientProvidedQosData> {
    constructor() {
        super("discord_protos.qos_token.v1.QosToken.ClientProvidedQosData", [
            { no: 1, name: "is_active", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<QosToken_ClientProvidedQosData>): QosToken_ClientProvidedQosData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isActive = false;
        if (value !== undefined)
            reflectionMergePartial<QosToken_ClientProvidedQosData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QosToken_ClientProvidedQosData): QosToken_ClientProvidedQosData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_active */ 1:
                    message.isActive = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QosToken_ClientProvidedQosData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_active = 1; */
        if (message.isActive !== false)
            writer.tag(1, WireType.Varint).bool(message.isActive);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.qos_token.v1.QosToken.ClientProvidedQosData
 */
export const QosToken_ClientProvidedQosData = new QosToken_ClientProvidedQosData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class QosToken_DerivedQosData$Type extends MessageType<QosToken_DerivedQosData> {
    constructor() {
        super("discord_protos.qos_token.v1.QosToken.DerivedQosData", [
            { no: 1, name: "claims", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<QosToken_DerivedQosData>): QosToken_DerivedQosData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.claims = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<QosToken_DerivedQosData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QosToken_DerivedQosData): QosToken_DerivedQosData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes claims */ 1:
                    message.claims = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: QosToken_DerivedQosData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes claims = 1; */
        if (message.claims.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.claims);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.qos_token.v1.QosToken.DerivedQosData
 */
export const QosToken_DerivedQosData = new QosToken_DerivedQosData$Type();
