"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class FrecencyUserSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _GIFType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _GIFTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FrecencyUserSettings._GIFType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        GIF_TYPE_NONE: FrecencyUserSettings._GIFType.ValueType  # 0
        GIF_TYPE_IMAGE: FrecencyUserSettings._GIFType.ValueType  # 1
        GIF_TYPE_VIDEO: FrecencyUserSettings._GIFType.ValueType  # 2

    class GIFType(_GIFType, metaclass=_GIFTypeEnumTypeWrapper): ...
    GIF_TYPE_NONE: FrecencyUserSettings.GIFType.ValueType  # 0
    GIF_TYPE_IMAGE: FrecencyUserSettings.GIFType.ValueType  # 1
    GIF_TYPE_VIDEO: FrecencyUserSettings.GIFType.ValueType  # 2

    @_typing.final
    class Versions(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CLIENT_VERSION_FIELD_NUMBER: _builtins.int
        SERVER_VERSION_FIELD_NUMBER: _builtins.int
        DATA_VERSION_FIELD_NUMBER: _builtins.int
        client_version: _builtins.int
        server_version: _builtins.int
        data_version: _builtins.int
        def __init__(
            self,
            *,
            client_version: _builtins.int = ...,
            server_version: _builtins.int = ...,
            data_version: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["client_version", b"client_version", "data_version", b"data_version", "server_version", b"server_version"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FavoriteGIF(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        FORMAT_FIELD_NUMBER: _builtins.int
        SRC_FIELD_NUMBER: _builtins.int
        WIDTH_FIELD_NUMBER: _builtins.int
        HEIGHT_FIELD_NUMBER: _builtins.int
        ORDER_FIELD_NUMBER: _builtins.int
        format: Global___FrecencyUserSettings.GIFType.ValueType
        src: _builtins.str
        width: _builtins.int
        height: _builtins.int
        order: _builtins.int
        def __init__(
            self,
            *,
            format: Global___FrecencyUserSettings.GIFType.ValueType = ...,
            src: _builtins.str = ...,
            width: _builtins.int = ...,
            height: _builtins.int = ...,
            order: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["format", b"format", "height", b"height", "order", b"order", "src", b"src", "width", b"width"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FavoriteGIFs(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class GifsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FavoriteGIF: ...
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: Global___FrecencyUserSettings.FavoriteGIF | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        GIFS_FIELD_NUMBER: _builtins.int
        HIDE_TOOLTIP_FIELD_NUMBER: _builtins.int
        hide_tooltip: _builtins.bool
        @_builtins.property
        def gifs(self) -> _containers.MessageMap[_builtins.str, Global___FrecencyUserSettings.FavoriteGIF]: ...
        def __init__(
            self,
            *,
            gifs: _abc.Mapping[_builtins.str, Global___FrecencyUserSettings.FavoriteGIF] | None = ...,
            hide_tooltip: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["gifs", b"gifs", "hide_tooltip", b"hide_tooltip"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FavoriteStickers(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STICKER_IDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sticker_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(
            self,
            *,
            sticker_ids: _abc.Iterable[_builtins.int] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sticker_ids", b"sticker_ids"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FrecencyItem(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TOTAL_USES_FIELD_NUMBER: _builtins.int
        RECENT_USES_FIELD_NUMBER: _builtins.int
        FRECENCY_FIELD_NUMBER: _builtins.int
        SCORE_FIELD_NUMBER: _builtins.int
        total_uses: _builtins.int
        frecency: _builtins.int
        score: _builtins.int
        @_builtins.property
        def recent_uses(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(
            self,
            *,
            total_uses: _builtins.int = ...,
            recent_uses: _abc.Iterable[_builtins.int] | None = ...,
            frecency: _builtins.int = ...,
            score: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["frecency", b"frecency", "recent_uses", b"recent_uses", "score", b"score", "total_uses", b"total_uses"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class StickerFrecency(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class StickersEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.int
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FrecencyItem: ...
            def __init__(
                self,
                *,
                key: _builtins.int = ...,
                value: Global___FrecencyUserSettings.FrecencyItem | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        STICKERS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def stickers(self) -> _containers.MessageMap[_builtins.int, Global___FrecencyUserSettings.FrecencyItem]: ...
        def __init__(
            self,
            *,
            stickers: _abc.Mapping[_builtins.int, Global___FrecencyUserSettings.FrecencyItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["stickers", b"stickers"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FavoriteEmojis(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        EMOJIS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def emojis(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(
            self,
            *,
            emojis: _abc.Iterable[_builtins.str] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["emojis", b"emojis"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class EmojiFrecency(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class EmojisEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FrecencyItem: ...
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: Global___FrecencyUserSettings.FrecencyItem | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        EMOJIS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def emojis(self) -> _containers.MessageMap[_builtins.str, Global___FrecencyUserSettings.FrecencyItem]: ...
        def __init__(
            self,
            *,
            emojis: _abc.Mapping[_builtins.str, Global___FrecencyUserSettings.FrecencyItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["emojis", b"emojis"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ApplicationCommandFrecency(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ApplicationCommandsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FrecencyItem: ...
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: Global___FrecencyUserSettings.FrecencyItem | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        APPLICATION_COMMANDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def application_commands(self) -> _containers.MessageMap[_builtins.str, Global___FrecencyUserSettings.FrecencyItem]: ...
        def __init__(
            self,
            *,
            application_commands: _abc.Mapping[_builtins.str, Global___FrecencyUserSettings.FrecencyItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["application_commands", b"application_commands"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FavoriteSoundboardSounds(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SOUND_IDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sound_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(
            self,
            *,
            sound_ids: _abc.Iterable[_builtins.int] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sound_ids", b"sound_ids"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class ApplicationFrecency(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ApplicationsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FrecencyItem: ...
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: Global___FrecencyUserSettings.FrecencyItem | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        APPLICATIONS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def applications(self) -> _containers.MessageMap[_builtins.str, Global___FrecencyUserSettings.FrecencyItem]: ...
        def __init__(
            self,
            *,
            applications: _abc.Mapping[_builtins.str, Global___FrecencyUserSettings.FrecencyItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["applications", b"applications"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class HeardSoundFrecency(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class HeardSoundsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FrecencyItem: ...
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: Global___FrecencyUserSettings.FrecencyItem | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        HEARD_SOUNDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def heard_sounds(self) -> _containers.MessageMap[_builtins.str, Global___FrecencyUserSettings.FrecencyItem]: ...
        def __init__(
            self,
            *,
            heard_sounds: _abc.Mapping[_builtins.str, Global___FrecencyUserSettings.FrecencyItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["heard_sounds", b"heard_sounds"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class PlayedSoundFrecency(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class PlayedSoundsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FrecencyItem: ...
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: Global___FrecencyUserSettings.FrecencyItem | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        PLAYED_SOUNDS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def played_sounds(self) -> _containers.MessageMap[_builtins.str, Global___FrecencyUserSettings.FrecencyItem]: ...
        def __init__(
            self,
            *,
            played_sounds: _abc.Mapping[_builtins.str, Global___FrecencyUserSettings.FrecencyItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["played_sounds", b"played_sounds"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class GuildAndChannelFrecency(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class GuildAndChannelsEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.int
            @_builtins.property
            def value(self) -> Global___FrecencyUserSettings.FrecencyItem: ...
            def __init__(
                self,
                *,
                key: _builtins.int = ...,
                value: Global___FrecencyUserSettings.FrecencyItem | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        GUILD_AND_CHANNELS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def guild_and_channels(self) -> _containers.MessageMap[_builtins.int, Global___FrecencyUserSettings.FrecencyItem]: ...
        def __init__(
            self,
            *,
            guild_and_channels: _abc.Mapping[_builtins.int, Global___FrecencyUserSettings.FrecencyItem] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["guild_and_channels", b"guild_and_channels"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    VERSIONS_FIELD_NUMBER: _builtins.int
    FAVORITE_GIFS_FIELD_NUMBER: _builtins.int
    FAVORITE_STICKERS_FIELD_NUMBER: _builtins.int
    STICKER_FRECENCY_FIELD_NUMBER: _builtins.int
    FAVORITE_EMOJIS_FIELD_NUMBER: _builtins.int
    EMOJI_FRECENCY_FIELD_NUMBER: _builtins.int
    APPLICATION_COMMAND_FRECENCY_FIELD_NUMBER: _builtins.int
    FAVORITE_SOUNDBOARD_SOUNDS_FIELD_NUMBER: _builtins.int
    APPLICATION_FRECENCY_FIELD_NUMBER: _builtins.int
    HEARD_SOUND_FRECENCY_FIELD_NUMBER: _builtins.int
    PLAYED_SOUND_FRECENCY_FIELD_NUMBER: _builtins.int
    GUILD_AND_CHANNEL_FRECENCY_FIELD_NUMBER: _builtins.int
    EMOJI_REACTION_FRECENCY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def versions(self) -> Global___FrecencyUserSettings.Versions: ...
    @_builtins.property
    def favorite_gifs(self) -> Global___FrecencyUserSettings.FavoriteGIFs: ...
    @_builtins.property
    def favorite_stickers(self) -> Global___FrecencyUserSettings.FavoriteStickers: ...
    @_builtins.property
    def sticker_frecency(self) -> Global___FrecencyUserSettings.StickerFrecency: ...
    @_builtins.property
    def favorite_emojis(self) -> Global___FrecencyUserSettings.FavoriteEmojis: ...
    @_builtins.property
    def emoji_frecency(self) -> Global___FrecencyUserSettings.EmojiFrecency: ...
    @_builtins.property
    def application_command_frecency(self) -> Global___FrecencyUserSettings.ApplicationCommandFrecency: ...
    @_builtins.property
    def favorite_soundboard_sounds(self) -> Global___FrecencyUserSettings.FavoriteSoundboardSounds: ...
    @_builtins.property
    def application_frecency(self) -> Global___FrecencyUserSettings.ApplicationFrecency: ...
    @_builtins.property
    def heard_sound_frecency(self) -> Global___FrecencyUserSettings.HeardSoundFrecency: ...
    @_builtins.property
    def played_sound_frecency(self) -> Global___FrecencyUserSettings.PlayedSoundFrecency: ...
    @_builtins.property
    def guild_and_channel_frecency(self) -> Global___FrecencyUserSettings.GuildAndChannelFrecency: ...
    @_builtins.property
    def emoji_reaction_frecency(self) -> Global___FrecencyUserSettings.EmojiFrecency: ...
    def __init__(
        self,
        *,
        versions: Global___FrecencyUserSettings.Versions | None = ...,
        favorite_gifs: Global___FrecencyUserSettings.FavoriteGIFs | None = ...,
        favorite_stickers: Global___FrecencyUserSettings.FavoriteStickers | None = ...,
        sticker_frecency: Global___FrecencyUserSettings.StickerFrecency | None = ...,
        favorite_emojis: Global___FrecencyUserSettings.FavoriteEmojis | None = ...,
        emoji_frecency: Global___FrecencyUserSettings.EmojiFrecency | None = ...,
        application_command_frecency: Global___FrecencyUserSettings.ApplicationCommandFrecency | None = ...,
        favorite_soundboard_sounds: Global___FrecencyUserSettings.FavoriteSoundboardSounds | None = ...,
        application_frecency: Global___FrecencyUserSettings.ApplicationFrecency | None = ...,
        heard_sound_frecency: Global___FrecencyUserSettings.HeardSoundFrecency | None = ...,
        played_sound_frecency: Global___FrecencyUserSettings.PlayedSoundFrecency | None = ...,
        guild_and_channel_frecency: Global___FrecencyUserSettings.GuildAndChannelFrecency | None = ...,
        emoji_reaction_frecency: Global___FrecencyUserSettings.EmojiFrecency | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_application_command_frecency", b"_application_command_frecency", "_application_frecency", b"_application_frecency", "_emoji_frecency", b"_emoji_frecency", "_emoji_reaction_frecency", b"_emoji_reaction_frecency", "_favorite_emojis", b"_favorite_emojis", "_favorite_gifs", b"_favorite_gifs", "_favorite_soundboard_sounds", b"_favorite_soundboard_sounds", "_favorite_stickers", b"_favorite_stickers", "_guild_and_channel_frecency", b"_guild_and_channel_frecency", "_heard_sound_frecency", b"_heard_sound_frecency", "_played_sound_frecency", b"_played_sound_frecency", "_sticker_frecency", b"_sticker_frecency", "_versions", b"_versions", "application_command_frecency", b"application_command_frecency", "application_frecency", b"application_frecency", "emoji_frecency", b"emoji_frecency", "emoji_reaction_frecency", b"emoji_reaction_frecency", "favorite_emojis", b"favorite_emojis", "favorite_gifs", b"favorite_gifs", "favorite_soundboard_sounds", b"favorite_soundboard_sounds", "favorite_stickers", b"favorite_stickers", "guild_and_channel_frecency", b"guild_and_channel_frecency", "heard_sound_frecency", b"heard_sound_frecency", "played_sound_frecency", b"played_sound_frecency", "sticker_frecency", b"sticker_frecency", "versions", b"versions"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_application_command_frecency", b"_application_command_frecency", "_application_frecency", b"_application_frecency", "_emoji_frecency", b"_emoji_frecency", "_emoji_reaction_frecency", b"_emoji_reaction_frecency", "_favorite_emojis", b"_favorite_emojis", "_favorite_gifs", b"_favorite_gifs", "_favorite_soundboard_sounds", b"_favorite_soundboard_sounds", "_favorite_stickers", b"_favorite_stickers", "_guild_and_channel_frecency", b"_guild_and_channel_frecency", "_heard_sound_frecency", b"_heard_sound_frecency", "_played_sound_frecency", b"_played_sound_frecency", "_sticker_frecency", b"_sticker_frecency", "_versions", b"_versions", "application_command_frecency", b"application_command_frecency", "application_frecency", b"application_frecency", "emoji_frecency", b"emoji_frecency", "emoji_reaction_frecency", b"emoji_reaction_frecency", "favorite_emojis", b"favorite_emojis", "favorite_gifs", b"favorite_gifs", "favorite_soundboard_sounds", b"favorite_soundboard_sounds", "favorite_stickers", b"favorite_stickers", "guild_and_channel_frecency", b"guild_and_channel_frecency", "heard_sound_frecency", b"heard_sound_frecency", "played_sound_frecency", b"played_sound_frecency", "sticker_frecency", b"sticker_frecency", "versions", b"versions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__application_command_frecency: _TypeAlias = _typing.Literal["application_command_frecency"]  # noqa: Y015
    _WhichOneofArgType__application_command_frecency: _TypeAlias = _typing.Literal["_application_command_frecency", b"_application_command_frecency"]  # noqa: Y015
    _WhichOneofReturnType__application_frecency: _TypeAlias = _typing.Literal["application_frecency"]  # noqa: Y015
    _WhichOneofArgType__application_frecency: _TypeAlias = _typing.Literal["_application_frecency", b"_application_frecency"]  # noqa: Y015
    _WhichOneofReturnType__emoji_frecency: _TypeAlias = _typing.Literal["emoji_frecency"]  # noqa: Y015
    _WhichOneofArgType__emoji_frecency: _TypeAlias = _typing.Literal["_emoji_frecency", b"_emoji_frecency"]  # noqa: Y015
    _WhichOneofReturnType__emoji_reaction_frecency: _TypeAlias = _typing.Literal["emoji_reaction_frecency"]  # noqa: Y015
    _WhichOneofArgType__emoji_reaction_frecency: _TypeAlias = _typing.Literal["_emoji_reaction_frecency", b"_emoji_reaction_frecency"]  # noqa: Y015
    _WhichOneofReturnType__favorite_emojis: _TypeAlias = _typing.Literal["favorite_emojis"]  # noqa: Y015
    _WhichOneofArgType__favorite_emojis: _TypeAlias = _typing.Literal["_favorite_emojis", b"_favorite_emojis"]  # noqa: Y015
    _WhichOneofReturnType__favorite_gifs: _TypeAlias = _typing.Literal["favorite_gifs"]  # noqa: Y015
    _WhichOneofArgType__favorite_gifs: _TypeAlias = _typing.Literal["_favorite_gifs", b"_favorite_gifs"]  # noqa: Y015
    _WhichOneofReturnType__favorite_soundboard_sounds: _TypeAlias = _typing.Literal["favorite_soundboard_sounds"]  # noqa: Y015
    _WhichOneofArgType__favorite_soundboard_sounds: _TypeAlias = _typing.Literal["_favorite_soundboard_sounds", b"_favorite_soundboard_sounds"]  # noqa: Y015
    _WhichOneofReturnType__favorite_stickers: _TypeAlias = _typing.Literal["favorite_stickers"]  # noqa: Y015
    _WhichOneofArgType__favorite_stickers: _TypeAlias = _typing.Literal["_favorite_stickers", b"_favorite_stickers"]  # noqa: Y015
    _WhichOneofReturnType__guild_and_channel_frecency: _TypeAlias = _typing.Literal["guild_and_channel_frecency"]  # noqa: Y015
    _WhichOneofArgType__guild_and_channel_frecency: _TypeAlias = _typing.Literal["_guild_and_channel_frecency", b"_guild_and_channel_frecency"]  # noqa: Y015
    _WhichOneofReturnType__heard_sound_frecency: _TypeAlias = _typing.Literal["heard_sound_frecency"]  # noqa: Y015
    _WhichOneofArgType__heard_sound_frecency: _TypeAlias = _typing.Literal["_heard_sound_frecency", b"_heard_sound_frecency"]  # noqa: Y015
    _WhichOneofReturnType__played_sound_frecency: _TypeAlias = _typing.Literal["played_sound_frecency"]  # noqa: Y015
    _WhichOneofArgType__played_sound_frecency: _TypeAlias = _typing.Literal["_played_sound_frecency", b"_played_sound_frecency"]  # noqa: Y015
    _WhichOneofReturnType__sticker_frecency: _TypeAlias = _typing.Literal["sticker_frecency"]  # noqa: Y015
    _WhichOneofArgType__sticker_frecency: _TypeAlias = _typing.Literal["_sticker_frecency", b"_sticker_frecency"]  # noqa: Y015
    _WhichOneofReturnType__versions: _TypeAlias = _typing.Literal["versions"]  # noqa: Y015
    _WhichOneofArgType__versions: _TypeAlias = _typing.Literal["_versions", b"_versions"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__application_command_frecency) -> _WhichOneofReturnType__application_command_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__application_frecency) -> _WhichOneofReturnType__application_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__emoji_frecency) -> _WhichOneofReturnType__emoji_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__emoji_reaction_frecency) -> _WhichOneofReturnType__emoji_reaction_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__favorite_emojis) -> _WhichOneofReturnType__favorite_emojis | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__favorite_gifs) -> _WhichOneofReturnType__favorite_gifs | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__favorite_soundboard_sounds) -> _WhichOneofReturnType__favorite_soundboard_sounds | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__favorite_stickers) -> _WhichOneofReturnType__favorite_stickers | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__guild_and_channel_frecency) -> _WhichOneofReturnType__guild_and_channel_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__heard_sound_frecency) -> _WhichOneofReturnType__heard_sound_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__played_sound_frecency) -> _WhichOneofReturnType__played_sound_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__sticker_frecency) -> _WhichOneofReturnType__sticker_frecency | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__versions) -> _WhichOneofReturnType__versions | None: ...

Global___FrecencyUserSettings: _TypeAlias = FrecencyUserSettings  # noqa: Y015
