"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AgreementsHistory(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class AgreementAcceptance(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ACCEPTED_AT_FIELD_NUMBER: _builtins.int
        VERSION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def accepted_at(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def version(self) -> _wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            accepted_at: _timestamp_pb2.Timestamp | None = ...,
            version: _wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_accepted_at", b"_accepted_at", "_version", b"_version", "accepted_at", b"accepted_at", "version", b"version"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_accepted_at", b"_accepted_at", "_version", b"_version", "accepted_at", b"accepted_at", "version", b"version"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__accepted_at: _TypeAlias = _typing.Literal["accepted_at"]  # noqa: Y015
        _WhichOneofArgType__accepted_at: _TypeAlias = _typing.Literal["_accepted_at", b"_accepted_at"]  # noqa: Y015
        _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
        _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__accepted_at) -> _WhichOneofReturnType__accepted_at | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

    TERMS_FIELD_NUMBER: _builtins.int
    PRIVACY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def terms(self) -> _containers.RepeatedCompositeFieldContainer[Global___AgreementsHistory.AgreementAcceptance]: ...
    @_builtins.property
    def privacy(self) -> _containers.RepeatedCompositeFieldContainer[Global___AgreementsHistory.AgreementAcceptance]: ...
    def __init__(
        self,
        *,
        terms: _abc.Iterable[Global___AgreementsHistory.AgreementAcceptance] | None = ...,
        privacy: _abc.Iterable[Global___AgreementsHistory.AgreementAcceptance] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["privacy", b"privacy", "terms", b"terms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AgreementsHistory: _TypeAlias = AgreementsHistory  # noqa: Y015
