# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users/v1/AgreementsHistory.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'users/v1/AgreementsHistory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n users/v1/AgreementsHistory.proto\x12\x17\x64iscord_protos.users.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x02\n\x11\x41greementsHistory\x12M\n\x05terms\x18\x01 \x03(\x0b\x32>.discord_protos.users.v1.AgreementsHistory.AgreementAcceptance\x12O\n\x07privacy\x18\x02 \x03(\x0b\x32>.discord_protos.users.v1.AgreementsHistory.AgreementAcceptance\x1a\x9b\x01\n\x13\x41greementAcceptance\x12\x34\n\x0b\x61\x63\x63\x65pted_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x32\n\x07version\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueH\x01\x88\x01\x01\x42\x0e\n\x0c_accepted_atB\n\n\x08_versionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users.v1.AgreementsHistory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGREEMENTSHISTORY']._serialized_start=127
  _globals['_AGREEMENTSHISTORY']._serialized_end=464
  _globals['_AGREEMENTSHISTORY_AGREEMENTACCEPTANCE']._serialized_start=309
  _globals['_AGREEMENTSHISTORY_AGREEMENTACCEPTANCE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
