# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qos_token/v1/QosToken.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'qos_token/v1/QosToken.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bqos_token/v1/QosToken.proto\x12\x1b\x64iscord_protos.qos_token.v1\"\x9f\x02\n\x08QosToken\x12Y\n\x0f\x63lient_provided\x18\x01 \x01(\x0b\x32;.discord_protos.qos_token.v1.QosToken.ClientProvidedQosDataH\x00\x88\x01\x01\x12J\n\x07\x64\x65rived\x18\x02 \x01(\x0b\x32\x34.discord_protos.qos_token.v1.QosToken.DerivedQosDataH\x01\x88\x01\x01\x1a*\n\x15\x43lientProvidedQosData\x12\x11\n\tis_active\x18\x01 \x01(\x08\x1a \n\x0e\x44\x65rivedQosData\x12\x0e\n\x06\x63laims\x18\x01 \x01(\x0c\x42\x12\n\x10_client_providedB\n\n\x08_derivedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qos_token.v1.QosToken_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QOSTOKEN']._serialized_start=61
  _globals['_QOSTOKEN']._serialized_end=348
  _globals['_QOSTOKEN_CLIENTPROVIDEDQOSDATA']._serialized_start=240
  _globals['_QOSTOKEN_CLIENTPROVIDEDQOSDATA']._serialized_end=282
  _globals['_QOSTOKEN_DERIVEDQOSDATA']._serialized_start=284
  _globals['_QOSTOKEN_DERIVEDQOSDATA']._serialized_end=316
# @@protoc_insertion_point(module_scope)
