"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class QosToken(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ClientProvidedQosData(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        IS_ACTIVE_FIELD_NUMBER: _builtins.int
        is_active: _builtins.bool
        def __init__(
            self,
            *,
            is_active: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["is_active", b"is_active"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DerivedQosData(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CLAIMS_FIELD_NUMBER: _builtins.int
        claims: _builtins.bytes
        def __init__(
            self,
            *,
            claims: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["claims", b"claims"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CLIENT_PROVIDED_FIELD_NUMBER: _builtins.int
    DERIVED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def client_provided(self) -> Global___QosToken.ClientProvidedQosData: ...
    @_builtins.property
    def derived(self) -> Global___QosToken.DerivedQosData: ...
    def __init__(
        self,
        *,
        client_provided: Global___QosToken.ClientProvidedQosData | None = ...,
        derived: Global___QosToken.DerivedQosData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_client_provided", b"_client_provided", "_derived", b"_derived", "client_provided", b"client_provided", "derived", b"derived"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_client_provided", b"_client_provided", "_derived", b"_derived", "client_provided", b"client_provided", "derived", b"derived"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__client_provided: _TypeAlias = _typing.Literal["client_provided"]  # noqa: Y015
    _WhichOneofArgType__client_provided: _TypeAlias = _typing.Literal["_client_provided", b"_client_provided"]  # noqa: Y015
    _WhichOneofReturnType__derived: _TypeAlias = _typing.Literal["derived"]  # noqa: Y015
    _WhichOneofArgType__derived: _TypeAlias = _typing.Literal["_derived", b"_derived"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__client_provided) -> _WhichOneofReturnType__client_provided | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__derived) -> _WhichOneofReturnType__derived | None: ...

Global___QosToken: _TypeAlias = QosToken  # noqa: Y015
