"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UserNotificationSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class EmailNotificationSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class CategoriesEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            value: _builtins.bool
            def __init__(
                self,
                *,
                key: _builtins.str = ...,
                value: _builtins.bool = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        CATEGORIES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def categories(self) -> _containers.ScalarMap[_builtins.str, _builtins.bool]: ...
        def __init__(
            self,
            *,
            categories: _abc.Mapping[_builtins.str, _builtins.bool] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["categories", b"categories"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class MuteNotificationSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        END_TIME_FIELD_NUMBER: _builtins.int
        SELECTED_TIME_WINDOW_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def end_time(self) -> _timestamp_pb2.Timestamp: ...
        @_builtins.property
        def selected_time_window(self) -> _wrappers_pb2.Int32Value: ...
        def __init__(
            self,
            *,
            end_time: _timestamp_pb2.Timestamp | None = ...,
            selected_time_window: _wrappers_pb2.Int32Value | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_end_time", b"_end_time", "_selected_time_window", b"_selected_time_window", "end_time", b"end_time", "selected_time_window", b"selected_time_window"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_end_time", b"_end_time", "_selected_time_window", b"_selected_time_window", "end_time", b"end_time", "selected_time_window", b"selected_time_window"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__end_time: _TypeAlias = _typing.Literal["end_time"]  # noqa: Y015
        _WhichOneofArgType__end_time: _TypeAlias = _typing.Literal["_end_time", b"_end_time"]  # noqa: Y015
        _WhichOneofReturnType__selected_time_window: _TypeAlias = _typing.Literal["selected_time_window"]  # noqa: Y015
        _WhichOneofArgType__selected_time_window: _TypeAlias = _typing.Literal["_selected_time_window", b"_selected_time_window"]  # noqa: Y015
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__end_time) -> _WhichOneofReturnType__end_time | None: ...
        @_typing.overload
        def WhichOneof(self, oneof_group: _WhichOneofArgType__selected_time_window) -> _WhichOneofReturnType__selected_time_window | None: ...

    @_typing.final
    class ChannelNotificationSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CHANNEL_ID_FIELD_NUMBER: _builtins.int
        MESSAGE_NOTIFICATIONS_FIELD_NUMBER: _builtins.int
        MUTE_FIELD_NUMBER: _builtins.int
        COLLAPSED_FIELD_NUMBER: _builtins.int
        channel_id: _builtins.int
        message_notifications: _builtins.int
        collapsed: _builtins.bool
        @_builtins.property
        def mute(self) -> Global___UserNotificationSettings.MuteNotificationSettings: ...
        def __init__(
            self,
            *,
            channel_id: _builtins.int = ...,
            message_notifications: _builtins.int = ...,
            mute: Global___UserNotificationSettings.MuteNotificationSettings | None = ...,
            collapsed: _builtins.bool = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_mute", b"_mute", "mute", b"mute"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_mute", b"_mute", "channel_id", b"channel_id", "collapsed", b"collapsed", "message_notifications", b"message_notifications", "mute", b"mute"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__mute: _TypeAlias = _typing.Literal["mute"]  # noqa: Y015
        _WhichOneofArgType__mute: _TypeAlias = _typing.Literal["_mute", b"_mute"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__mute) -> _WhichOneofReturnType__mute | None: ...

    @_typing.final
    class GuildNotificationSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SUPPRESS_EVERYONE_FIELD_NUMBER: _builtins.int
        MESSAGE_NOTIFICATIONS_FIELD_NUMBER: _builtins.int
        MOBILE_PUSH_FIELD_NUMBER: _builtins.int
        MUTE_FIELD_NUMBER: _builtins.int
        CHANNEL_OVERRIDES_FIELD_NUMBER: _builtins.int
        SUPPRESS_ROLES_FIELD_NUMBER: _builtins.int
        VERSION_FIELD_NUMBER: _builtins.int
        HIDE_MUTED_CHANNELS_FIELD_NUMBER: _builtins.int
        MUTE_SCHEDULED_EVENTS_FIELD_NUMBER: _builtins.int
        NOTIFY_HIGHLIGHTS_FIELD_NUMBER: _builtins.int
        suppress_everyone: _builtins.bool
        message_notifications: _builtins.int
        mobile_push: _builtins.bool
        suppress_roles: _builtins.bool
        version: _builtins.int
        hide_muted_channels: _builtins.bool
        mute_scheduled_events: _builtins.bool
        notify_highlights: _builtins.int
        @_builtins.property
        def mute(self) -> Global___UserNotificationSettings.MuteNotificationSettings: ...
        @_builtins.property
        def channel_overrides(self) -> _containers.RepeatedCompositeFieldContainer[Global___UserNotificationSettings.ChannelNotificationSettings]: ...
        def __init__(
            self,
            *,
            suppress_everyone: _builtins.bool = ...,
            message_notifications: _builtins.int = ...,
            mobile_push: _builtins.bool = ...,
            mute: Global___UserNotificationSettings.MuteNotificationSettings | None = ...,
            channel_overrides: _abc.Iterable[Global___UserNotificationSettings.ChannelNotificationSettings] | None = ...,
            suppress_roles: _builtins.bool = ...,
            version: _builtins.int = ...,
            hide_muted_channels: _builtins.bool = ...,
            mute_scheduled_events: _builtins.bool = ...,
            notify_highlights: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_mute", b"_mute", "mute", b"mute"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_mute", b"_mute", "channel_overrides", b"channel_overrides", "hide_muted_channels", b"hide_muted_channels", "message_notifications", b"message_notifications", "mobile_push", b"mobile_push", "mute", b"mute", "mute_scheduled_events", b"mute_scheduled_events", "notify_highlights", b"notify_highlights", "suppress_everyone", b"suppress_everyone", "suppress_roles", b"suppress_roles", "version", b"version"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__mute: _TypeAlias = _typing.Literal["mute"]  # noqa: Y015
        _WhichOneofArgType__mute: _TypeAlias = _typing.Literal["_mute", b"_mute"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__mute) -> _WhichOneofReturnType__mute | None: ...

    @_typing.final
    class Versions(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CLIENT_VERSION_FIELD_NUMBER: _builtins.int
        SERVER_VERSION_FIELD_NUMBER: _builtins.int
        DATA_VERSION_FIELD_NUMBER: _builtins.int
        client_version: _builtins.int
        server_version: _builtins.int
        data_version: _builtins.int
        def __init__(
            self,
            *,
            client_version: _builtins.int = ...,
            server_version: _builtins.int = ...,
            data_version: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["client_version", b"client_version", "data_version", b"data_version", "server_version", b"server_version"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeclarativeNotifSetting(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        TOGGLE_FIELD_NUMBER: _builtins.int
        RADIO_FIELD_NUMBER: _builtins.int
        toggle: _builtins.bool
        radio: _builtins.int
        def __init__(
            self,
            *,
            toggle: _builtins.bool = ...,
            radio: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["radio", b"radio", "toggle", b"toggle"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DeclarativeSettings(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ValuesEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.int
            @_builtins.property
            def value(self) -> Global___UserNotificationSettings.DeclarativeNotifSetting: ...
            def __init__(
                self,
                *,
                key: _builtins.int = ...,
                value: Global___UserNotificationSettings.DeclarativeNotifSetting | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        VERSIONS_FIELD_NUMBER: _builtins.int
        VALUES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def versions(self) -> Global___UserNotificationSettings.Versions: ...
        @_builtins.property
        def values(self) -> _containers.MessageMap[_builtins.int, Global___UserNotificationSettings.DeclarativeNotifSetting]: ...
        def __init__(
            self,
            *,
            versions: Global___UserNotificationSettings.Versions | None = ...,
            values: _abc.Mapping[_builtins.int, Global___UserNotificationSettings.DeclarativeNotifSetting] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_versions", b"_versions", "versions", b"versions"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_versions", b"_versions", "values", b"values", "versions", b"versions"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__versions: _TypeAlias = _typing.Literal["versions"]  # noqa: Y015
        _WhichOneofArgType__versions: _TypeAlias = _typing.Literal["_versions", b"_versions"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__versions) -> _WhichOneofReturnType__versions | None: ...

    @_typing.final
    class UserNotificationSettingsData(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class MutedGamesEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.int
            value: _builtins.bool
            def __init__(
                self,
                *,
                key: _builtins.int = ...,
                value: _builtins.bool = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        MUTED_GAMES_FIELD_NUMBER: _builtins.int
        DECLARATIVE_SETTINGS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def muted_games(self) -> _containers.ScalarMap[_builtins.int, _builtins.bool]: ...
        @_builtins.property
        def declarative_settings(self) -> Global___UserNotificationSettings.DeclarativeSettings: ...
        def __init__(
            self,
            *,
            muted_games: _abc.Mapping[_builtins.int, _builtins.bool] | None = ...,
            declarative_settings: Global___UserNotificationSettings.DeclarativeSettings | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_declarative_settings", b"_declarative_settings", "declarative_settings", b"declarative_settings"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_declarative_settings", b"_declarative_settings", "declarative_settings", b"declarative_settings", "muted_games", b"muted_games"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__declarative_settings: _TypeAlias = _typing.Literal["declarative_settings"]  # noqa: Y015
        _WhichOneofArgType__declarative_settings: _TypeAlias = _typing.Literal["_declarative_settings", b"_declarative_settings"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__declarative_settings) -> _WhichOneofReturnType__declarative_settings | None: ...

    @_typing.final
    class GuildsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___UserNotificationSettings.GuildNotificationSettings: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___UserNotificationSettings.GuildNotificationSettings | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    USER_ID_FIELD_NUMBER: _builtins.int
    EMAIL_SETTINGS_FIELD_NUMBER: _builtins.int
    FLAGS_FIELD_NUMBER: _builtins.int
    GUILDS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    user_id: _builtins.int
    version: _builtins.int
    @_builtins.property
    def email_settings(self) -> Global___UserNotificationSettings.EmailNotificationSettings: ...
    @_builtins.property
    def flags(self) -> _wrappers_pb2.UInt64Value: ...
    @_builtins.property
    def guilds(self) -> _containers.MessageMap[_builtins.int, Global___UserNotificationSettings.GuildNotificationSettings]: ...
    @_builtins.property
    def data(self) -> Global___UserNotificationSettings.UserNotificationSettingsData: ...
    def __init__(
        self,
        *,
        user_id: _builtins.int = ...,
        email_settings: Global___UserNotificationSettings.EmailNotificationSettings | None = ...,
        flags: _wrappers_pb2.UInt64Value | None = ...,
        guilds: _abc.Mapping[_builtins.int, Global___UserNotificationSettings.GuildNotificationSettings] | None = ...,
        version: _builtins.int = ...,
        data: Global___UserNotificationSettings.UserNotificationSettingsData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_data", b"_data", "_email_settings", b"_email_settings", "_flags", b"_flags", "data", b"data", "email_settings", b"email_settings", "flags", b"flags"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_data", b"_data", "_email_settings", b"_email_settings", "_flags", b"_flags", "data", b"data", "email_settings", b"email_settings", "flags", b"flags", "guilds", b"guilds", "user_id", b"user_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__data: _TypeAlias = _typing.Literal["data"]  # noqa: Y015
    _WhichOneofArgType__data: _TypeAlias = _typing.Literal["_data", b"_data"]  # noqa: Y015
    _WhichOneofReturnType__email_settings: _TypeAlias = _typing.Literal["email_settings"]  # noqa: Y015
    _WhichOneofArgType__email_settings: _TypeAlias = _typing.Literal["_email_settings", b"_email_settings"]  # noqa: Y015
    _WhichOneofReturnType__flags: _TypeAlias = _typing.Literal["flags"]  # noqa: Y015
    _WhichOneofArgType__flags: _TypeAlias = _typing.Literal["_flags", b"_flags"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__data) -> _WhichOneofReturnType__data | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__email_settings) -> _WhichOneofReturnType__email_settings | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__flags) -> _WhichOneofReturnType__flags | None: ...

Global___UserNotificationSettings: _TypeAlias = UserNotificationSettings  # noqa: Y015
