"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AcknowledgedApplicationDisclosures(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ApplicationDisclosureType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ApplicationDisclosureTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[AcknowledgedApplicationDisclosures._ApplicationDisclosureType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        APPLICATION_DISCLOSURE_TYPE_UNSPECIFIED_DISCLOSURE: AcknowledgedApplicationDisclosures._ApplicationDisclosureType.ValueType  # 0
        APPLICATION_DISCLOSURE_TYPE_IP_LOCATION: AcknowledgedApplicationDisclosures._ApplicationDisclosureType.ValueType  # 1
        APPLICATION_DISCLOSURE_TYPE_DISPLAYS_ADVERTISEMENTS: AcknowledgedApplicationDisclosures._ApplicationDisclosureType.ValueType  # 2
        APPLICATION_DISCLOSURE_TYPE_PARTNER_SDK_DATA_SHARING_MESSAGE: AcknowledgedApplicationDisclosures._ApplicationDisclosureType.ValueType  # 3

    class ApplicationDisclosureType(_ApplicationDisclosureType, metaclass=_ApplicationDisclosureTypeEnumTypeWrapper): ...
    APPLICATION_DISCLOSURE_TYPE_UNSPECIFIED_DISCLOSURE: AcknowledgedApplicationDisclosures.ApplicationDisclosureType.ValueType  # 0
    APPLICATION_DISCLOSURE_TYPE_IP_LOCATION: AcknowledgedApplicationDisclosures.ApplicationDisclosureType.ValueType  # 1
    APPLICATION_DISCLOSURE_TYPE_DISPLAYS_ADVERTISEMENTS: AcknowledgedApplicationDisclosures.ApplicationDisclosureType.ValueType  # 2
    APPLICATION_DISCLOSURE_TYPE_PARTNER_SDK_DATA_SHARING_MESSAGE: AcknowledgedApplicationDisclosures.ApplicationDisclosureType.ValueType  # 3

    @_typing.final
    class AcknowledgedApplicationDisclosure(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DISCLOSURE_TYPE_FIELD_NUMBER: _builtins.int
        ACKED_AT_FIELD_NUMBER: _builtins.int
        disclosure_type: Global___AcknowledgedApplicationDisclosures.ApplicationDisclosureType.ValueType
        @_builtins.property
        def acked_at(self) -> _timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            disclosure_type: Global___AcknowledgedApplicationDisclosures.ApplicationDisclosureType.ValueType = ...,
            acked_at: _timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["_acked_at", b"_acked_at", "acked_at", b"acked_at"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["_acked_at", b"_acked_at", "acked_at", b"acked_at", "disclosure_type", b"disclosure_type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType__acked_at: _TypeAlias = _typing.Literal["acked_at"]  # noqa: Y015
        _WhichOneofArgType__acked_at: _TypeAlias = _typing.Literal["_acked_at", b"_acked_at"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType__acked_at) -> _WhichOneofReturnType__acked_at | None: ...

    ACKED_DISCLOSURES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def acked_disclosures(self) -> _containers.RepeatedCompositeFieldContainer[Global___AcknowledgedApplicationDisclosures.AcknowledgedApplicationDisclosure]: ...
    def __init__(
        self,
        *,
        acked_disclosures: _abc.Iterable[Global___AcknowledgedApplicationDisclosures.AcknowledgedApplicationDisclosure] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acked_disclosures", b"acked_disclosures"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AcknowledgedApplicationDisclosures: _TypeAlias = AcknowledgedApplicationDisclosures  # noqa: Y015
