// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "users/v1/AgreementsHistory.proto" (package "discord_protos.users.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../google/protobuf/wrappers";
import { Timestamp } from "../../google/protobuf/timestamp";
/**
 * @generated from protobuf message discord_protos.users.v1.AgreementsHistory
 */
export interface AgreementsHistory {
    /**
     * @generated from protobuf field: repeated discord_protos.users.v1.AgreementsHistory.AgreementAcceptance terms = 1
     */
    terms: AgreementsHistory_AgreementAcceptance[];
    /**
     * @generated from protobuf field: repeated discord_protos.users.v1.AgreementsHistory.AgreementAcceptance privacy = 2
     */
    privacy: AgreementsHistory_AgreementAcceptance[];
}
/**
 * @generated from protobuf message discord_protos.users.v1.AgreementsHistory.AgreementAcceptance
 */
export interface AgreementsHistory_AgreementAcceptance {
    /**
     * @generated from protobuf field: optional google.protobuf.Timestamp accepted_at = 1
     */
    acceptedAt?: Timestamp;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue version = 2
     */
    version?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class AgreementsHistory$Type extends MessageType<AgreementsHistory> {
    constructor() {
        super("discord_protos.users.v1.AgreementsHistory", [
            { no: 1, name: "terms", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AgreementsHistory_AgreementAcceptance },
            { no: 2, name: "privacy", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AgreementsHistory_AgreementAcceptance }
        ]);
    }
    create(value?: PartialMessage<AgreementsHistory>): AgreementsHistory {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.terms = [];
        message.privacy = [];
        if (value !== undefined)
            reflectionMergePartial<AgreementsHistory>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AgreementsHistory): AgreementsHistory {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated discord_protos.users.v1.AgreementsHistory.AgreementAcceptance terms */ 1:
                    message.terms.push(AgreementsHistory_AgreementAcceptance.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated discord_protos.users.v1.AgreementsHistory.AgreementAcceptance privacy */ 2:
                    message.privacy.push(AgreementsHistory_AgreementAcceptance.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgreementsHistory, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated discord_protos.users.v1.AgreementsHistory.AgreementAcceptance terms = 1; */
        for (let i = 0; i < message.terms.length; i++)
            AgreementsHistory_AgreementAcceptance.internalBinaryWrite(message.terms[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated discord_protos.users.v1.AgreementsHistory.AgreementAcceptance privacy = 2; */
        for (let i = 0; i < message.privacy.length; i++)
            AgreementsHistory_AgreementAcceptance.internalBinaryWrite(message.privacy[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.AgreementsHistory
 */
export const AgreementsHistory = new AgreementsHistory$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AgreementsHistory_AgreementAcceptance$Type extends MessageType<AgreementsHistory_AgreementAcceptance> {
    constructor() {
        super("discord_protos.users.v1.AgreementsHistory.AgreementAcceptance", [
            { no: 1, name: "accepted_at", kind: "message", T: () => Timestamp },
            { no: 2, name: "version", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<AgreementsHistory_AgreementAcceptance>): AgreementsHistory_AgreementAcceptance {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<AgreementsHistory_AgreementAcceptance>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AgreementsHistory_AgreementAcceptance): AgreementsHistory_AgreementAcceptance {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Timestamp accepted_at */ 1:
                    message.acceptedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.acceptedAt);
                    break;
                case /* optional google.protobuf.StringValue version */ 2:
                    message.version = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.version);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AgreementsHistory_AgreementAcceptance, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Timestamp accepted_at = 1; */
        if (message.acceptedAt)
            Timestamp.internalBinaryWrite(message.acceptedAt, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue version = 2; */
        if (message.version)
            StringValue.internalBinaryWrite(message.version, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.AgreementsHistory.AgreementAcceptance
 */
export const AgreementsHistory_AgreementAcceptance = new AgreementsHistory_AgreementAcceptance$Type();
