# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: discord_experimentation/v1/Bucket/AllocationAssignmentMode.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'discord_experimentation/v1/Bucket/AllocationAssignmentMode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@discord_experimentation/v1/Bucket/AllocationAssignmentMode.proto\x12\x30\x64iscord_protos.discord_experimentation.v1.Bucket\"\x1a\n\x18\x41llocationAssignmentModeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discord_experimentation.v1.Bucket.AllocationAssignmentMode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLOCATIONASSIGNMENTMODE']._serialized_start=118
  _globals['_ALLOCATIONASSIGNMENTMODE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
