// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "discord_notifications/v1/UserNotificationSettings.proto" (package "discord_protos.discord_notifications.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Int32Value } from "../../google/protobuf/wrappers";
import { Timestamp } from "../../google/protobuf/timestamp";
import { UInt64Value } from "../../google/protobuf/wrappers";
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings
 */
export interface UserNotificationSettings {
    /**
     * @generated from protobuf field: fixed64 user_id = 1
     */
    userId: bigint;
    /**
     * @generated from protobuf field: optional discord_protos.discord_notifications.v1.UserNotificationSettings.EmailNotificationSettings email_settings = 2
     */
    emailSettings?: UserNotificationSettings_EmailNotificationSettings;
    /**
     * @generated from protobuf field: optional google.protobuf.UInt64Value flags = 6
     */
    flags?: UInt64Value;
    /**
     * @generated from protobuf field: map<fixed64, discord_protos.discord_notifications.v1.UserNotificationSettings.GuildNotificationSettings> guilds = 4
     */
    guilds: {
        [key: string]: UserNotificationSettings_GuildNotificationSettings;
    };
    /**
     * @generated from protobuf field: uint32 version = 5
     */
    version: number;
    /**
     * @generated from protobuf field: optional discord_protos.discord_notifications.v1.UserNotificationSettings.UserNotificationSettingsData data = 7
     */
    data?: UserNotificationSettings_UserNotificationSettingsData;
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.EmailNotificationSettings
 */
export interface UserNotificationSettings_EmailNotificationSettings {
    /**
     * @generated from protobuf field: map<string, bool> categories = 1
     */
    categories: {
        [key: string]: boolean;
    };
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings
 */
export interface UserNotificationSettings_MuteNotificationSettings {
    /**
     * @generated from protobuf field: optional google.protobuf.Timestamp end_time = 1
     */
    endTime?: Timestamp;
    /**
     * @generated from protobuf field: optional google.protobuf.Int32Value selected_time_window = 2
     */
    selectedTimeWindow?: Int32Value;
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.ChannelNotificationSettings
 */
export interface UserNotificationSettings_ChannelNotificationSettings {
    /**
     * @generated from protobuf field: fixed64 channel_id = 1
     */
    channelId: bigint;
    /**
     * @generated from protobuf field: uint32 message_notifications = 7
     */
    messageNotifications: number;
    /**
     * @generated from protobuf field: optional discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings mute = 3
     */
    mute?: UserNotificationSettings_MuteNotificationSettings;
    /**
     * @generated from protobuf field: bool collapsed = 4
     */
    collapsed: boolean;
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.GuildNotificationSettings
 */
export interface UserNotificationSettings_GuildNotificationSettings {
    /**
     * @generated from protobuf field: bool suppress_everyone = 1
     */
    suppressEveryone: boolean;
    /**
     * @generated from protobuf field: uint32 message_notifications = 2
     */
    messageNotifications: number;
    /**
     * @generated from protobuf field: bool mobile_push = 3
     */
    mobilePush: boolean;
    /**
     * @generated from protobuf field: optional discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings mute = 4
     */
    mute?: UserNotificationSettings_MuteNotificationSettings;
    /**
     * @generated from protobuf field: repeated discord_protos.discord_notifications.v1.UserNotificationSettings.ChannelNotificationSettings channel_overrides = 5
     */
    channelOverrides: UserNotificationSettings_ChannelNotificationSettings[];
    /**
     * @generated from protobuf field: bool suppress_roles = 6
     */
    suppressRoles: boolean;
    /**
     * @generated from protobuf field: uint32 version = 7
     */
    version: number;
    /**
     * @generated from protobuf field: bool hide_muted_channels = 8
     */
    hideMutedChannels: boolean;
    /**
     * @generated from protobuf field: bool mute_scheduled_events = 9
     */
    muteScheduledEvents: boolean;
    /**
     * @generated from protobuf field: uint32 notify_highlights = 10
     */
    notifyHighlights: number;
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.Versions
 */
export interface UserNotificationSettings_Versions {
    /**
     * @generated from protobuf field: uint32 client_version = 1
     */
    clientVersion: number;
    /**
     * @generated from protobuf field: uint32 server_version = 2
     */
    serverVersion: number;
    /**
     * @generated from protobuf field: uint32 data_version = 3
     */
    dataVersion: number;
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeNotifSetting
 */
export interface UserNotificationSettings_DeclarativeNotifSetting {
    /**
     * @generated from protobuf field: bool toggle = 1
     */
    toggle: boolean;
    /**
     * @generated from protobuf field: uint32 radio = 2
     */
    radio: number;
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeSettings
 */
export interface UserNotificationSettings_DeclarativeSettings {
    /**
     * @generated from protobuf field: optional discord_protos.discord_notifications.v1.UserNotificationSettings.Versions versions = 1
     */
    versions?: UserNotificationSettings_Versions;
    /**
     * @generated from protobuf field: map<uint32, discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeNotifSetting> values = 2
     */
    values: {
        [key: number]: UserNotificationSettings_DeclarativeNotifSetting;
    };
}
/**
 * @generated from protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.UserNotificationSettingsData
 */
export interface UserNotificationSettings_UserNotificationSettingsData {
    /**
     * @generated from protobuf field: map<fixed64, bool> muted_games = 1
     */
    mutedGames: {
        [key: string]: boolean;
    };
    /**
     * @generated from protobuf field: optional discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeSettings declarative_settings = 2
     */
    declarativeSettings?: UserNotificationSettings_DeclarativeSettings;
}
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings$Type extends MessageType<UserNotificationSettings> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings", [
            { no: 1, name: "user_id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "email_settings", kind: "message", T: () => UserNotificationSettings_EmailNotificationSettings },
            { no: 6, name: "flags", kind: "message", T: () => UInt64Value },
            { no: 4, name: "guilds", kind: "map", K: 6 /*ScalarType.FIXED64*/, V: { kind: "message", T: () => UserNotificationSettings_GuildNotificationSettings } },
            { no: 5, name: "version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "data", kind: "message", T: () => UserNotificationSettings_UserNotificationSettingsData }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings>): UserNotificationSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = 0n;
        message.guilds = {};
        message.version = 0;
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings): UserNotificationSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 user_id */ 1:
                    message.userId = reader.fixed64().toBigInt();
                    break;
                case /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.EmailNotificationSettings email_settings */ 2:
                    message.emailSettings = UserNotificationSettings_EmailNotificationSettings.internalBinaryRead(reader, reader.uint32(), options, message.emailSettings);
                    break;
                case /* optional google.protobuf.UInt64Value flags */ 6:
                    message.flags = UInt64Value.internalBinaryRead(reader, reader.uint32(), options, message.flags);
                    break;
                case /* map<fixed64, discord_protos.discord_notifications.v1.UserNotificationSettings.GuildNotificationSettings> guilds */ 4:
                    this.binaryReadMap4(message.guilds, reader, options);
                    break;
                case /* uint32 version */ 5:
                    message.version = reader.uint32();
                    break;
                case /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.UserNotificationSettingsData data */ 7:
                    message.data = UserNotificationSettings_UserNotificationSettingsData.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap4(map: UserNotificationSettings["guilds"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof UserNotificationSettings["guilds"] | undefined, val: UserNotificationSettings["guilds"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.fixed64().toString();
                    break;
                case 2:
                    val = UserNotificationSettings_GuildNotificationSettings.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for discord_protos.discord_notifications.v1.UserNotificationSettings.guilds");
            }
        }
        map[key ?? "0"] = val ?? UserNotificationSettings_GuildNotificationSettings.create();
    }
    internalBinaryWrite(message: UserNotificationSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 user_id = 1; */
        if (message.userId !== 0n)
            writer.tag(1, WireType.Bit64).fixed64(message.userId);
        /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.EmailNotificationSettings email_settings = 2; */
        if (message.emailSettings)
            UserNotificationSettings_EmailNotificationSettings.internalBinaryWrite(message.emailSettings, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* map<fixed64, discord_protos.discord_notifications.v1.UserNotificationSettings.GuildNotificationSettings> guilds = 4; */
        for (let k of globalThis.Object.keys(message.guilds)) {
            writer.tag(4, WireType.LengthDelimited).fork().tag(1, WireType.Bit64).fixed64(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            UserNotificationSettings_GuildNotificationSettings.internalBinaryWrite(message.guilds[k], writer, options);
            writer.join().join();
        }
        /* uint32 version = 5; */
        if (message.version !== 0)
            writer.tag(5, WireType.Varint).uint32(message.version);
        /* optional google.protobuf.UInt64Value flags = 6; */
        if (message.flags)
            UInt64Value.internalBinaryWrite(message.flags, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.UserNotificationSettingsData data = 7; */
        if (message.data)
            UserNotificationSettings_UserNotificationSettingsData.internalBinaryWrite(message.data, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings
 */
export const UserNotificationSettings = new UserNotificationSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_EmailNotificationSettings$Type extends MessageType<UserNotificationSettings_EmailNotificationSettings> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.EmailNotificationSettings", [
            { no: 1, name: "categories", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 8 /*ScalarType.BOOL*/ } }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_EmailNotificationSettings>): UserNotificationSettings_EmailNotificationSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.categories = {};
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_EmailNotificationSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_EmailNotificationSettings): UserNotificationSettings_EmailNotificationSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* map<string, bool> categories */ 1:
                    this.binaryReadMap1(message.categories, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap1(map: UserNotificationSettings_EmailNotificationSettings["categories"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof UserNotificationSettings_EmailNotificationSettings["categories"] | undefined, val: UserNotificationSettings_EmailNotificationSettings["categories"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.bool();
                    break;
                default: throw new globalThis.Error("unknown map entry field for discord_protos.discord_notifications.v1.UserNotificationSettings.EmailNotificationSettings.categories");
            }
        }
        map[key ?? ""] = val ?? false;
    }
    internalBinaryWrite(message: UserNotificationSettings_EmailNotificationSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* map<string, bool> categories = 1; */
        for (let k of globalThis.Object.keys(message.categories))
            writer.tag(1, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.Varint).bool(message.categories[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.EmailNotificationSettings
 */
export const UserNotificationSettings_EmailNotificationSettings = new UserNotificationSettings_EmailNotificationSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_MuteNotificationSettings$Type extends MessageType<UserNotificationSettings_MuteNotificationSettings> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings", [
            { no: 1, name: "end_time", kind: "message", T: () => Timestamp },
            { no: 2, name: "selected_time_window", kind: "message", T: () => Int32Value }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_MuteNotificationSettings>): UserNotificationSettings_MuteNotificationSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_MuteNotificationSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_MuteNotificationSettings): UserNotificationSettings_MuteNotificationSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Timestamp end_time */ 1:
                    message.endTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.endTime);
                    break;
                case /* optional google.protobuf.Int32Value selected_time_window */ 2:
                    message.selectedTimeWindow = Int32Value.internalBinaryRead(reader, reader.uint32(), options, message.selectedTimeWindow);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserNotificationSettings_MuteNotificationSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Timestamp end_time = 1; */
        if (message.endTime)
            Timestamp.internalBinaryWrite(message.endTime, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Int32Value selected_time_window = 2; */
        if (message.selectedTimeWindow)
            Int32Value.internalBinaryWrite(message.selectedTimeWindow, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings
 */
export const UserNotificationSettings_MuteNotificationSettings = new UserNotificationSettings_MuteNotificationSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_ChannelNotificationSettings$Type extends MessageType<UserNotificationSettings_ChannelNotificationSettings> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.ChannelNotificationSettings", [
            { no: 1, name: "channel_id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "message_notifications", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "mute", kind: "message", T: () => UserNotificationSettings_MuteNotificationSettings },
            { no: 4, name: "collapsed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_ChannelNotificationSettings>): UserNotificationSettings_ChannelNotificationSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.channelId = 0n;
        message.messageNotifications = 0;
        message.collapsed = false;
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_ChannelNotificationSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_ChannelNotificationSettings): UserNotificationSettings_ChannelNotificationSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 channel_id */ 1:
                    message.channelId = reader.fixed64().toBigInt();
                    break;
                case /* uint32 message_notifications */ 7:
                    message.messageNotifications = reader.uint32();
                    break;
                case /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings mute */ 3:
                    message.mute = UserNotificationSettings_MuteNotificationSettings.internalBinaryRead(reader, reader.uint32(), options, message.mute);
                    break;
                case /* bool collapsed */ 4:
                    message.collapsed = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserNotificationSettings_ChannelNotificationSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 channel_id = 1; */
        if (message.channelId !== 0n)
            writer.tag(1, WireType.Bit64).fixed64(message.channelId);
        /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings mute = 3; */
        if (message.mute)
            UserNotificationSettings_MuteNotificationSettings.internalBinaryWrite(message.mute, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bool collapsed = 4; */
        if (message.collapsed !== false)
            writer.tag(4, WireType.Varint).bool(message.collapsed);
        /* uint32 message_notifications = 7; */
        if (message.messageNotifications !== 0)
            writer.tag(7, WireType.Varint).uint32(message.messageNotifications);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.ChannelNotificationSettings
 */
export const UserNotificationSettings_ChannelNotificationSettings = new UserNotificationSettings_ChannelNotificationSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_GuildNotificationSettings$Type extends MessageType<UserNotificationSettings_GuildNotificationSettings> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.GuildNotificationSettings", [
            { no: 1, name: "suppress_everyone", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "message_notifications", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "mobile_push", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "mute", kind: "message", T: () => UserNotificationSettings_MuteNotificationSettings },
            { no: 5, name: "channel_overrides", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => UserNotificationSettings_ChannelNotificationSettings },
            { no: 6, name: "suppress_roles", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "hide_muted_channels", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "mute_scheduled_events", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "notify_highlights", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_GuildNotificationSettings>): UserNotificationSettings_GuildNotificationSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.suppressEveryone = false;
        message.messageNotifications = 0;
        message.mobilePush = false;
        message.channelOverrides = [];
        message.suppressRoles = false;
        message.version = 0;
        message.hideMutedChannels = false;
        message.muteScheduledEvents = false;
        message.notifyHighlights = 0;
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_GuildNotificationSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_GuildNotificationSettings): UserNotificationSettings_GuildNotificationSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool suppress_everyone */ 1:
                    message.suppressEveryone = reader.bool();
                    break;
                case /* uint32 message_notifications */ 2:
                    message.messageNotifications = reader.uint32();
                    break;
                case /* bool mobile_push */ 3:
                    message.mobilePush = reader.bool();
                    break;
                case /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings mute */ 4:
                    message.mute = UserNotificationSettings_MuteNotificationSettings.internalBinaryRead(reader, reader.uint32(), options, message.mute);
                    break;
                case /* repeated discord_protos.discord_notifications.v1.UserNotificationSettings.ChannelNotificationSettings channel_overrides */ 5:
                    message.channelOverrides.push(UserNotificationSettings_ChannelNotificationSettings.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool suppress_roles */ 6:
                    message.suppressRoles = reader.bool();
                    break;
                case /* uint32 version */ 7:
                    message.version = reader.uint32();
                    break;
                case /* bool hide_muted_channels */ 8:
                    message.hideMutedChannels = reader.bool();
                    break;
                case /* bool mute_scheduled_events */ 9:
                    message.muteScheduledEvents = reader.bool();
                    break;
                case /* uint32 notify_highlights */ 10:
                    message.notifyHighlights = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserNotificationSettings_GuildNotificationSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool suppress_everyone = 1; */
        if (message.suppressEveryone !== false)
            writer.tag(1, WireType.Varint).bool(message.suppressEveryone);
        /* uint32 message_notifications = 2; */
        if (message.messageNotifications !== 0)
            writer.tag(2, WireType.Varint).uint32(message.messageNotifications);
        /* bool mobile_push = 3; */
        if (message.mobilePush !== false)
            writer.tag(3, WireType.Varint).bool(message.mobilePush);
        /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.MuteNotificationSettings mute = 4; */
        if (message.mute)
            UserNotificationSettings_MuteNotificationSettings.internalBinaryWrite(message.mute, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated discord_protos.discord_notifications.v1.UserNotificationSettings.ChannelNotificationSettings channel_overrides = 5; */
        for (let i = 0; i < message.channelOverrides.length; i++)
            UserNotificationSettings_ChannelNotificationSettings.internalBinaryWrite(message.channelOverrides[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* bool suppress_roles = 6; */
        if (message.suppressRoles !== false)
            writer.tag(6, WireType.Varint).bool(message.suppressRoles);
        /* uint32 version = 7; */
        if (message.version !== 0)
            writer.tag(7, WireType.Varint).uint32(message.version);
        /* bool hide_muted_channels = 8; */
        if (message.hideMutedChannels !== false)
            writer.tag(8, WireType.Varint).bool(message.hideMutedChannels);
        /* bool mute_scheduled_events = 9; */
        if (message.muteScheduledEvents !== false)
            writer.tag(9, WireType.Varint).bool(message.muteScheduledEvents);
        /* uint32 notify_highlights = 10; */
        if (message.notifyHighlights !== 0)
            writer.tag(10, WireType.Varint).uint32(message.notifyHighlights);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.GuildNotificationSettings
 */
export const UserNotificationSettings_GuildNotificationSettings = new UserNotificationSettings_GuildNotificationSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_Versions$Type extends MessageType<UserNotificationSettings_Versions> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.Versions", [
            { no: 1, name: "client_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "server_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "data_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_Versions>): UserNotificationSettings_Versions {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.clientVersion = 0;
        message.serverVersion = 0;
        message.dataVersion = 0;
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_Versions>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_Versions): UserNotificationSettings_Versions {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 client_version */ 1:
                    message.clientVersion = reader.uint32();
                    break;
                case /* uint32 server_version */ 2:
                    message.serverVersion = reader.uint32();
                    break;
                case /* uint32 data_version */ 3:
                    message.dataVersion = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserNotificationSettings_Versions, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 client_version = 1; */
        if (message.clientVersion !== 0)
            writer.tag(1, WireType.Varint).uint32(message.clientVersion);
        /* uint32 server_version = 2; */
        if (message.serverVersion !== 0)
            writer.tag(2, WireType.Varint).uint32(message.serverVersion);
        /* uint32 data_version = 3; */
        if (message.dataVersion !== 0)
            writer.tag(3, WireType.Varint).uint32(message.dataVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.Versions
 */
export const UserNotificationSettings_Versions = new UserNotificationSettings_Versions$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_DeclarativeNotifSetting$Type extends MessageType<UserNotificationSettings_DeclarativeNotifSetting> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeNotifSetting", [
            { no: 1, name: "toggle", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "radio", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_DeclarativeNotifSetting>): UserNotificationSettings_DeclarativeNotifSetting {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.toggle = false;
        message.radio = 0;
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_DeclarativeNotifSetting>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_DeclarativeNotifSetting): UserNotificationSettings_DeclarativeNotifSetting {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool toggle */ 1:
                    message.toggle = reader.bool();
                    break;
                case /* uint32 radio */ 2:
                    message.radio = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UserNotificationSettings_DeclarativeNotifSetting, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool toggle = 1; */
        if (message.toggle !== false)
            writer.tag(1, WireType.Varint).bool(message.toggle);
        /* uint32 radio = 2; */
        if (message.radio !== 0)
            writer.tag(2, WireType.Varint).uint32(message.radio);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeNotifSetting
 */
export const UserNotificationSettings_DeclarativeNotifSetting = new UserNotificationSettings_DeclarativeNotifSetting$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_DeclarativeSettings$Type extends MessageType<UserNotificationSettings_DeclarativeSettings> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeSettings", [
            { no: 1, name: "versions", kind: "message", T: () => UserNotificationSettings_Versions },
            { no: 2, name: "values", kind: "map", K: 13 /*ScalarType.UINT32*/, V: { kind: "message", T: () => UserNotificationSettings_DeclarativeNotifSetting } }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_DeclarativeSettings>): UserNotificationSettings_DeclarativeSettings {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.values = {};
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_DeclarativeSettings>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_DeclarativeSettings): UserNotificationSettings_DeclarativeSettings {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.Versions versions */ 1:
                    message.versions = UserNotificationSettings_Versions.internalBinaryRead(reader, reader.uint32(), options, message.versions);
                    break;
                case /* map<uint32, discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeNotifSetting> values */ 2:
                    this.binaryReadMap2(message.values, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: UserNotificationSettings_DeclarativeSettings["values"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof UserNotificationSettings_DeclarativeSettings["values"] | undefined, val: UserNotificationSettings_DeclarativeSettings["values"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.uint32();
                    break;
                case 2:
                    val = UserNotificationSettings_DeclarativeNotifSetting.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeSettings.values");
            }
        }
        map[key ?? 0] = val ?? UserNotificationSettings_DeclarativeNotifSetting.create();
    }
    internalBinaryWrite(message: UserNotificationSettings_DeclarativeSettings, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.Versions versions = 1; */
        if (message.versions)
            UserNotificationSettings_Versions.internalBinaryWrite(message.versions, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* map<uint32, discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeNotifSetting> values = 2; */
        for (let k of globalThis.Object.keys(message.values)) {
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.Varint).uint32(parseInt(k));
            writer.tag(2, WireType.LengthDelimited).fork();
            UserNotificationSettings_DeclarativeNotifSetting.internalBinaryWrite(message.values[k as any], writer, options);
            writer.join().join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeSettings
 */
export const UserNotificationSettings_DeclarativeSettings = new UserNotificationSettings_DeclarativeSettings$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserNotificationSettings_UserNotificationSettingsData$Type extends MessageType<UserNotificationSettings_UserNotificationSettingsData> {
    constructor() {
        super("discord_protos.discord_notifications.v1.UserNotificationSettings.UserNotificationSettingsData", [
            { no: 1, name: "muted_games", kind: "map", K: 6 /*ScalarType.FIXED64*/, V: { kind: "scalar", T: 8 /*ScalarType.BOOL*/ } },
            { no: 2, name: "declarative_settings", kind: "message", T: () => UserNotificationSettings_DeclarativeSettings }
        ]);
    }
    create(value?: PartialMessage<UserNotificationSettings_UserNotificationSettingsData>): UserNotificationSettings_UserNotificationSettingsData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.mutedGames = {};
        if (value !== undefined)
            reflectionMergePartial<UserNotificationSettings_UserNotificationSettingsData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UserNotificationSettings_UserNotificationSettingsData): UserNotificationSettings_UserNotificationSettingsData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* map<fixed64, bool> muted_games */ 1:
                    this.binaryReadMap1(message.mutedGames, reader, options);
                    break;
                case /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeSettings declarative_settings */ 2:
                    message.declarativeSettings = UserNotificationSettings_DeclarativeSettings.internalBinaryRead(reader, reader.uint32(), options, message.declarativeSettings);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap1(map: UserNotificationSettings_UserNotificationSettingsData["mutedGames"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof UserNotificationSettings_UserNotificationSettingsData["mutedGames"] | undefined, val: UserNotificationSettings_UserNotificationSettingsData["mutedGames"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.fixed64().toString();
                    break;
                case 2:
                    val = reader.bool();
                    break;
                default: throw new globalThis.Error("unknown map entry field for discord_protos.discord_notifications.v1.UserNotificationSettings.UserNotificationSettingsData.muted_games");
            }
        }
        map[key ?? "0"] = val ?? false;
    }
    internalBinaryWrite(message: UserNotificationSettings_UserNotificationSettingsData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* map<fixed64, bool> muted_games = 1; */
        for (let k of globalThis.Object.keys(message.mutedGames))
            writer.tag(1, WireType.LengthDelimited).fork().tag(1, WireType.Bit64).fixed64(k).tag(2, WireType.Varint).bool(message.mutedGames[k]).join();
        /* optional discord_protos.discord_notifications.v1.UserNotificationSettings.DeclarativeSettings declarative_settings = 2; */
        if (message.declarativeSettings)
            UserNotificationSettings_DeclarativeSettings.internalBinaryWrite(message.declarativeSettings, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.discord_notifications.v1.UserNotificationSettings.UserNotificationSettingsData
 */
export const UserNotificationSettings_UserNotificationSettingsData = new UserNotificationSettings_UserNotificationSettingsData$Type();
