name: Update definitions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install
    - run: npm run load
    - run: npm run build
    - run: npm run test

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update protobuf definitions
