// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "common/v1/LocalizedSnowflake.proto" (package "discord_protos.common.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message discord_protos.common.v1.LocalizedSnowflake
 */
export interface LocalizedSnowflake {
    /**
     * @generated from protobuf field: fixed64 default = 1
     */
    default: bigint;
    /**
     * @generated from protobuf field: map<string, fixed64> localizations = 2
     */
    localizations: {
        [key: string]: bigint;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class LocalizedSnowflake$Type extends MessageType<LocalizedSnowflake> {
    constructor() {
        super("discord_protos.common.v1.LocalizedSnowflake", [
            { no: 1, name: "default", kind: "scalar", T: 6 /*ScalarType.FIXED64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "localizations", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 6 /*ScalarType.FIXED64*/, L: 0 /*LongType.BIGINT*/ } }
        ]);
    }
    create(value?: PartialMessage<LocalizedSnowflake>): LocalizedSnowflake {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.default = 0n;
        message.localizations = {};
        if (value !== undefined)
            reflectionMergePartial<LocalizedSnowflake>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalizedSnowflake): LocalizedSnowflake {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 default */ 1:
                    message.default = reader.fixed64().toBigInt();
                    break;
                case /* map<string, fixed64> localizations */ 2:
                    this.binaryReadMap2(message.localizations, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap2(map: LocalizedSnowflake["localizations"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof LocalizedSnowflake["localizations"] | undefined, val: LocalizedSnowflake["localizations"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.fixed64().toBigInt();
                    break;
                default: throw new globalThis.Error("unknown map entry field for discord_protos.common.v1.LocalizedSnowflake.localizations");
            }
        }
        map[key ?? ""] = val ?? 0n;
    }
    internalBinaryWrite(message: LocalizedSnowflake, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 default = 1; */
        if (message.default !== 0n)
            writer.tag(1, WireType.Bit64).fixed64(message.default);
        /* map<string, fixed64> localizations = 2; */
        for (let k of globalThis.Object.keys(message.localizations))
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.Bit64).fixed64(message.localizations[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.common.v1.LocalizedSnowflake
 */
export const LocalizedSnowflake = new LocalizedSnowflake$Type();
